In [93]:
%pip install pandas openpyxl

import pandas as pd

Requirement already satisfied: pandas in /Users/sonylnagale/Documents/CIS 9655 (Spring 2026)/midterm datasets/.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: openpyxl in /Users/sonylnagale/Documents/CIS 9655 (Spring 2026)/midterm datasets/.venv/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: numpy>=2.3.3 in /Users/sonylnagale/Documents/CIS 9655 (Spring 2026)/midterm datasets/.venv/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sonylnagale/Documents/CIS 9655 (Spring 2026)/midterm datasets/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /Users/sonylnagale/Documents/CIS 9655 (Spring 2026)/midterm datasets/.venv/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /Users/sonylnagale/Documents/CIS 9655 (Spring 2026)/midterm datasets/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [94]:
# Human Development Reports
df = pd.read_csv('./HDR25_Composite_indices_complete_time_series.csv', encoding='latin-1')

df

,iso3,country,hdicode,region,hdi_rank_2023,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,pop_total_2014,pop_total_2015,pop_total_2016,pop_total_2017,pop_total_2018,pop_total_2019,pop_total_2020,pop_total_2021,pop_total_2022,pop_total_2023
0,AFG,Afghanistan,Low,SA,181.0,0.285,0.291,0.301,0.311,0.305,...,32.792523,33.831764,34.700612,35.688935,36.743039,37.856121,39.068979,40.000412,40.578842,41.454761
1,ALB,Albania,Very High,ECA,71.0,0.654,0.638,0.622,0.624,0.629,...,2.903749,2.898632,2.897867,2.898242,2.894231,2.885009,2.871954,2.849636,2.827608,2.811655
2,DZA,Algeria,High,AS,96.0,0.595,0.596,0.601,0.603,0.603,...,39.205030,40.019529,40.850721,41.689299,42.505035,43.294546,44.042091,44.761099,45.477390,46.164219
3,AND,Andorra,Very High,NaN,32.0,NaN,NaN,NaN,NaN,NaN,...,0.073737,0.072174,0.072181,0.073762,0.075162,0.076473,0.077380,0.078364,0.079705,0.080856
4,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,27.160770,28.157798,29.183070,30.234839,31.297155,32.375633,33.451132,34.532429,35.635029,36.749906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,ZZG.ECA,Europe and Central Asia,NaN,NaN,NaN,0.674,0.671,0.664,0.659,0.654,...,237.933850,240.937124,243.649817,246.131011,248.450885,250.382485,252.050998,253.404866,251.911694,250.300624
202,ZZH.LAC,Latin America and the Caribbean,NaN,NaN,NaN,0.648,0.653,0.657,0.661,0.666,...,608.767281,614.831634,620.753858,626.503607,632.005592,637.185739,641.737540,645.501309,649.425289,653.952733
203,ZZI.SA,South Asia,NaN,NaN,NaN,0.454,0.458,0.464,0.468,0.472,...,1849.167918,1871.872058,1894.465346,1917.144604,1939.537762,1961.729204,1983.510394,2003.263428,2022.467288,2043.083160
204,ZZJ.SSA,Sub-Saharan Africa,NaN,NaN,NaN,0.405,0.409,0.408,0.411,0.413,...,945.842319,971.462925,997.258713,1023.353059,1050.355450,1077.776785,1105.614070,1133.710593,1162.042581,1191.521675
205,ZZK.WORLD,World,NaN,NaN,NaN,0.608,0.611,0.614,0.617,0.620,...,7347.587459,7436.429577,7524.460416,7611.536549,7695.833415,7777.189671,7852.891001,7920.440021,7987.545028,8057.957339

In [95]:
meta = pd.read_excel('./HDR25_Composite_indices_metadata.xlsx', sheet_name='codebook')

meta

,Full name,Short name,Time series
0,ISO3,iso3,-
1,HDR Country Name,country,-
2,Human Development Groups,hdicode,-
3,UNDP Developeing Regions,region,-
4,HDI,NaN,NaN
5,HDI Rank,hdi_rank,2023
6,Human Development Index (value),hdi,1990-2023
7,Life Expectancy at Birth (years),le,1990-2023
8,Expected Years of Schooling (years),eys,1990-2023
9,Mean Years of Schooling (years),mys,1990-2023
10,Gross National Income Per Capita (2021 PPP$),gnipc,1990-2023
11,GDI,NaN,NaN
12,GDI Group,gdi_group,2023
13,Gender Development Index (value),gdi,1990-2023
14,HDI female (value),hdi_f,1990-2023
15,"Life Expectancy at Birth, female (years)",le_f,1990-2023
16,"Expected Years of Schooling, female (years)",eys_f,1990-2023
17,"Mean Years of Schooling, female (years)",mys_f,1990-2023
18,"Gross National Income Per Capita, female (2021...",gni_pc_f,1990-2023
19,HDI male (value),hdi_m,1990-2023
20,"Life Expectancy at Birth, male (years)",le_m,1990-2023
21,"Expected Years of Schooling, male (years)",eys_m,1990-2023
22,"Mean Years of Schooling, male (years)",mys_m,1990-2023
23,"Gross National Income Per Capita, male (2021 P...",gni_pc_m,1990-2023
24,IHDI,NaN,NaN
25,Inequality-adjusted Human Development Index (v...,ihdi,2010-2023
26,Coefficient of human inequality,coef_ineq,2010-2023
27,Overall loss (%),loss,2010-2023
28,Inequality in life expectancy,ineq_le,2010-2023
29,Inequality in eduation,ineq_edu,2010-2023
30,Inequality in income,ineq_inc,"2010-2021, 2022-2023=2022"
31,GII,NaN,NaN
32,GII Rank,gii_rank,2023
33,Gender Inequality Index (value),gii,1990-2023
34,"Maternal Mortality Ratio (deaths per 100,000 l...",mmr,"1990-2019, 2020-2023=2020"
35,"Adolescent Birth Rate (births per 1,000 women ...",abr,1990-2023
36,Population with at least some secondary educat...,se_f,1990-2023
37,Population with at least some secondary educat...,se_m,1990-2023
38,"Share of seats in parliament, female (% held b...",pr_f,1990-2023
39,"Share of seats in parliament, male (% held by ...",pr_m,1990-2023
40,"Labour force participation rate, female (% age...",lfpr_f,1990-2023
41,"Labour force participation rate, male (% ages ...",lfpr_m,1990-2023
42,PHDI,NaN,NaN
43,Difference from HDI rank,rankdiff_hdi_phdi,2023
44,Planetary pressures–adjusted Human Development...,phdi,1990-2023
45,Difference from HDI value (%),diff_hdi_phdi,1990-2023
46,Carbon dioxide emissions per capita (productio...,co2_prod,1990-2023
47,Material footprint per capita (tonnes),mf,1990-2023
48,Additional Indicator,NaN,NaN
49,"Population, total (millions)",pop_total,1990-2023

In [165]:
pattern = r'\d{4}-\d{4}'  # Matches any 4-digit year
mask = meta['Time series'].str.contains(pattern, regex=True, na=False)
# Get the field names which have time series data for a range of years
fields = meta.loc[mask, 'Full name'].tolist()

fields

['Human Development Index (value)',
 'Life Expectancy at Birth (years)',
 'Expected Years of Schooling (years)',
 'Mean Years of Schooling (years)',
 'Gross National Income Per Capita (2021 PPP$)',
 'Gender Development Index (value)',
 'HDI female (value)',
 'Life Expectancy at Birth, female (years)',
 'Expected Years of Schooling, female (years)',
 'Mean Years of Schooling, female (years)',
 'Gross National Income Per Capita, female (2021 PPP$)',
 'HDI male (value)',
 'Life Expectancy at Birth, male (years)',
 'Expected Years of Schooling, male (years)',
 'Mean Years of Schooling, male (years)',
 'Gross National Income Per Capita, male (2021 PPP$)',
 'Inequality-adjusted Human Development Index (value)',
 'Coefficient of human inequality',
 'Overall loss (%)',
 'Inequality in life expectancy',
 'Inequality in eduation',
 'Inequality in income',
 'Gender Inequality Index (value)',
 'Maternal Mortality Ratio (deaths per 100,000 live births)',
 'Adolescent Birth Rate (births per 1,000 women ages 15-19)',
 'Population with at least some secondary education, female (% ages 25 and older)',
 'Population with at least some secondary education, male (% ages 25 and older)',
 'Share of seats in parliament, female (% held by women)',
 'Share of seats in parliament, male (% held by men)',
 'Labour force participation rate, female (% ages 15 and older)',
 'Labour force participation rate, male (% ages 15 and older)',
 'Planetary pressures–adjusted Human Development Index (value)',
 'Difference from HDI value (%)',
 'Carbon dioxide emissions per capita (production) (tonnes)',
 'Material footprint per capita (tonnes)',
 'Population, total (millions)']

In [ ]:
import re

# Rename columns based on the metadata, replacing short names with long names but keeping the year so we can melt
df_renamed = df.rename(columns={col: re.sub(r'(.*)_(\d{4})', lambda m: meta.loc[meta['Short name'] == m.group(1), 'Full name'].values[0] + f": {m.group(2)}", col) for col in df.columns})
df_renamed

,iso3,country,hdicode,region,HDI Rank: 2023,Human Development Index (value): 1990,Human Development Index (value): 1991,Human Development Index (value): 1992,Human Development Index (value): 1993,Human Development Index (value): 1994,...,"Population, total (millions): 2014","Population, total (millions): 2015","Population, total (millions): 2016","Population, total (millions): 2017","Population, total (millions): 2018","Population, total (millions): 2019","Population, total (millions): 2020","Population, total (millions): 2021","Population, total (millions): 2022","Population, total (millions): 2023"
0,AFG,Afghanistan,Low,SA,181.0,0.285,0.291,0.301,0.311,0.305,...,32.792523,33.831764,34.700612,35.688935,36.743039,37.856121,39.068979,40.000412,40.578842,41.454761
1,ALB,Albania,Very High,ECA,71.0,0.654,0.638,0.622,0.624,0.629,...,2.903749,2.898632,2.897867,2.898242,2.894231,2.885009,2.871954,2.849636,2.827608,2.811655
2,DZA,Algeria,High,AS,96.0,0.595,0.596,0.601,0.603,0.603,...,39.205030,40.019529,40.850721,41.689299,42.505035,43.294546,44.042091,44.761099,45.477390,46.164219
3,AND,Andorra,Very High,NaN,32.0,NaN,NaN,NaN,NaN,NaN,...,0.073737,0.072174,0.072181,0.073762,0.075162,0.076473,0.077380,0.078364,0.079705,0.080856
4,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,27.160770,28.157798,29.183070,30.234839,31.297155,32.375633,33.451132,34.532429,35.635029,36.749906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,ZZG.ECA,Europe and Central Asia,NaN,NaN,NaN,0.674,0.671,0.664,0.659,0.654,...,237.933850,240.937124,243.649817,246.131011,248.450885,250.382485,252.050998,253.404866,251.911694,250.300624
202,ZZH.LAC,Latin America and the Caribbean,NaN,NaN,NaN,0.648,0.653,0.657,0.661,0.666,...,608.767281,614.831634,620.753858,626.503607,632.005592,637.185739,641.737540,645.501309,649.425289,653.952733
203,ZZI.SA,South Asia,NaN,NaN,NaN,0.454,0.458,0.464,0.468,0.472,...,1849.167918,1871.872058,1894.465346,1917.144604,1939.537762,1961.729204,1983.510394,2003.263428,2022.467288,2043.083160
204,ZZJ.SSA,Sub-Saharan Africa,NaN,NaN,NaN,0.405,0.409,0.408,0.411,0.413,...,945.842319,971.462925,997.258713,1023.353059,1050.355450,1077.776785,1105.614070,1133.710593,1162.042581,1191.521675
205,ZZK.WORLD,World,NaN,NaN,NaN,0.608,0.611,0.614,0.617,0.620,...,7347.587459,7436.429577,7524.460416,7611.536549,7695.833415,7777.189671,7852.891001,7920.440021,7987.545028,8057.957339

In [ ]:
# manipulate the dataframe to get the fields melted into long format (years in a single column, values in other column)
df_long = pd.wide_to_long(df_renamed, stubnames=fields,
                          i=['iso3'], 
                          j='Year', 
                          sep=': ').reset_index()

df_long

,iso3,Year,Difference from HDI rank: 2023,GDI Group: 2023,GII Rank: 2023,HDI Rank: 2023,country,hdicode,region,Human Development Index (value),...,"Population with at least some secondary education, male (% ages 25 and older)","Share of seats in parliament, female (% held by women)","Share of seats in parliament, male (% held by men)","Labour force participation rate, female (% ages 15 and older)","Labour force participation rate, male (% ages 15 and older)",Planetary pressures–adjusted Human Development Index (value),Difference from HDI value (%),Carbon dioxide emissions per capita (production) (tonnes),Material footprint per capita (tonnes),"Population, total (millions)"
0,AFG,1990,5.0,5.0,168.0,181.0,Afghanistan,Low,SA,0.285,...,7.135089,NaN,NaN,NaN,NaN,0.281,1.403509,0.189279,2.024500,12.045660
1,ALB,1990,35.0,2.0,35.0,71.0,Albania,Very High,ECA,0.654,...,67.010180,NaN,NaN,45.220000,50.780000,0.605,7.492355,1.675414,11.512700,3.277966
2,DZA,1990,18.0,5.0,114.0,96.0,Algeria,High,AS,0.595,...,23.123883,3.157895,96.842105,NaN,NaN,0.560,5.882353,3.007186,6.938700,25.375810
3,AND,1990,NaN,NaN,NaN,32.0,Andorra,Very High,NaN,NaN,...,NaN,7.142857,92.857143,NaN,NaN,NaN,NaN,7.592078,NaN,0.052597
4,AGO,1990,11.0,4.0,139.0,148.0,Angola,Medium,SSA,NaN,...,NaN,9.545455,90.454545,NaN,NaN,NaN,NaN,0.430303,3.106100,11.626359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6999,ZZG.ECA,2023,NaN,NaN,NaN,NaN,Europe and Central Asia,NaN,NaN,0.818,...,90.332858,25.970549,74.029451,45.693821,69.254007,0.731,10.635697,5.031805,13.317783,250.300624
7000,ZZH.LAC,2023,NaN,NaN,NaN,NaN,Latin America and the Caribbean,NaN,NaN,0.783,...,66.082055,34.206784,65.793216,51.788140,75.113716,0.715,8.684547,2.681737,12.512788,653.952733
7001,ZZI.SA,2023,NaN,NaN,NaN,NaN,South Asia,NaN,NaN,0.672,...,58.871672,17.891817,82.108183,33.500455,76.678941,0.644,4.166667,2.097097,4.969705,2043.083160
7002,ZZJ.SSA,2023,NaN,NaN,NaN,NaN,Sub-Saharan Africa,NaN,NaN,0.568,...,43.827070,27.279188,72.720812,64.257465,75.578529,0.553,2.640845,0.681075,3.830108,1191.521675
7003,ZZK.WORLD,2023,NaN,NaN,NaN,NaN,World,NaN,NaN,0.756,...,70.196964,26.543715,73.456285,48.474078,74.122674,0.680,10.052910,4.535806,12.714085,8057.957339

In [ ]:
# Now, make a separate aggregates dataframe

aggregates = df_long[df_long['iso3'].str.contains('\\.')].reset_index(drop=True)
aggregates.dropna(axis=1, how='all', inplace=True)
aggregates

,iso3,Year,country,Human Development Index (value),Life Expectancy at Birth (years),Expected Years of Schooling (years),Mean Years of Schooling (years),Gross National Income Per Capita (2021 PPP$),Gender Development Index (value),HDI female (value),...,"Population with at least some secondary education, male (% ages 25 and older)","Share of seats in parliament, female (% held by women)","Share of seats in parliament, male (% held by men)","Labour force participation rate, female (% ages 15 and older)","Labour force participation rate, male (% ages 15 and older)",Planetary pressures–adjusted Human Development Index (value),Difference from HDI value (%),Carbon dioxide emissions per capita (production) (tonnes),Material footprint per capita (tonnes),"Population, total (millions)"
0,ZZA.VHHD,1990,Very high human development,0.797,73.974337,13.298931,9.843827,32836.902550,0.964,0.783642,...,71.935308,13.693760,86.306240,50.866244,74.443802,0.633,20.577164,11.909324,23.053318,1323.573229
1,ZZB.HHD,1990,High human development,0.569,67.106351,9.668976,4.616145,5332.249104,NaN,NaN,...,39.369887,NaN,NaN,NaN,NaN,0.542,4.745167,2.422811,5.754408,2215.981629
2,ZZC.MHD,1990,Medium human development,0.439,56.822195,7.551369,2.917411,2491.756633,NaN,NaN,...,27.561335,8.510024,91.489976,NaN,NaN,0.430,2.050114,0.582125,2.978182,1370.837247
3,ZZD.LHD,1990,Low human development,0.346,51.705900,4.108008,2.072413,2148.744490,NaN,NaN,...,20.676560,NaN,NaN,NaN,NaN,0.340,1.734104,0.289445,2.880003,366.484421
4,ZZE.AS,1990,Arab States,0.550,62.810957,8.154479,3.886564,11043.375370,NaN,NaN,...,30.315954,3.604558,96.395442,NaN,NaN,0.522,5.090909,2.685515,5.979314,220.948637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,ZZG.ECA,2023,Europe and Central Asia,0.818,74.789363,15.557345,10.696732,23171.472180,0.970,0.803291,...,90.332858,25.970549,74.029451,45.693821,69.254007,0.731,10.635697,5.031805,13.317783,250.300624
370,ZZH.LAC,2023,Latin America and the Caribbean,0.783,75.611256,14.772934,9.129518,18047.956160,0.989,0.776691,...,66.082055,34.206784,65.793216,51.788140,75.113716,0.715,8.684547,2.681737,12.512788,653.952733
371,ZZI.SA,2023,South Asia,0.672,71.869415,12.148221,6.793586,8722.022592,0.872,0.617966,...,58.871672,17.891817,82.108183,33.500455,76.678941,0.644,4.166667,2.097097,4.969705,2043.083160
372,ZZJ.SSA,2023,Sub-Saharan Africa,0.568,62.506277,10.345610,6.163414,4351.554920,0.916,0.543981,...,43.827070,27.279188,72.720812,64.257465,75.578529,0.553,2.640845,0.681075,3.830108,1191.521675
373,ZZK.WORLD,2023,World,0.756,73.383398,13.040366,8.775209,20327.308720,0.955,0.736825,...,70.196964,26.543715,73.456285,48.474078,74.122674,0.680,10.052910,4.535806,12.714085,8057.957339

In [ ]:
# Do the reverse for the country-level data.

df_long = df_long[~df_long['iso3'].str.contains('\\.')].reset_index(drop=True)
df_long

,iso3,Year,Difference from HDI rank: 2023,GDI Group: 2023,GII Rank: 2023,HDI Rank: 2023,country,hdicode,region,Human Development Index (value),...,"Population with at least some secondary education, male (% ages 25 and older)","Share of seats in parliament, female (% held by women)","Share of seats in parliament, male (% held by men)","Labour force participation rate, female (% ages 15 and older)","Labour force participation rate, male (% ages 15 and older)",Planetary pressures–adjusted Human Development Index (value),Difference from HDI value (%),Carbon dioxide emissions per capita (production) (tonnes),Material footprint per capita (tonnes),"Population, total (millions)"
0,AFG,1990,5.0,5.0,168.0,181.0,Afghanistan,Low,SA,0.285,...,7.135089,NaN,NaN,NaN,NaN,0.281,1.403509,0.189279,2.0245,12.045660
1,ALB,1990,35.0,2.0,35.0,71.0,Albania,Very High,ECA,0.654,...,67.010180,NaN,NaN,45.22,50.78,0.605,7.492355,1.675414,11.5127,3.277966
2,DZA,1990,18.0,5.0,114.0,96.0,Algeria,High,AS,0.595,...,23.123883,3.157895,96.842105,NaN,NaN,0.560,5.882353,3.007186,6.9387,25.375810
3,AND,1990,NaN,NaN,NaN,32.0,Andorra,Very High,NaN,NaN,...,NaN,7.142857,92.857143,NaN,NaN,NaN,NaN,7.592078,NaN,0.052597
4,AGO,1990,11.0,4.0,139.0,148.0,Angola,Medium,SSA,NaN,...,NaN,9.545455,90.454545,NaN,NaN,NaN,NaN,0.430303,3.1061,11.626359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6625,VEN,2023,7.0,1.0,137.0,121.0,Venezuela (Bolivarian Republic of),High,LAC,0.709,...,72.373742,22.155689,77.844311,47.23,71.79,0.652,8.039492,3.452638,10.3951,28.300854
6626,VNM,2023,9.0,1.0,78.0,93.0,Viet Nam,High,EAP,0.766,...,69.954536,30.260521,69.739479,67.92,76.65,0.699,8.746736,3.385896,11.7251,100.352192
6627,YEM,2023,1.0,5.0,172.0,184.0,Yemen,Low,AS,0.470,...,47.161251,0.298507,99.701493,5.91,65.70,0.465,1.063830,0.291290,1.6274,39.390799
6628,ZMB,2023,9.0,3.0,141.0,154.0,Zambia,Medium,SSA,0.595,...,52.880474,14.970060,85.029940,56.37,67.77,0.585,1.680672,0.376714,2.6774,20.723965
6629,ZWE,2023,8.0,3.0,140.0,153.0,Zimbabwe,Medium,SSA,0.598,...,92.861351,34.011628,65.988372,62.10,74.35,0.585,2.173913,0.669891,3.1335,16.340822

In [181]:
# output the data for use in Tableau if you want

df_long.to_csv('./human_development.csv', index=False)
aggregates.to_csv('./human_development_aggregates.csv', index=False)