In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
url = "https://raw.githubusercontent.com/shreyakarki71/energy-viz-project/main/energy-viz-project/energy-consumption-by-source-and-country.csv"

df = pd.read_csv(url)

In [ ]:
print(df.shape)
print(df.columns)
df.head()

(8317, 12)
Index(['Entity', 'Code', 'Year', 'Other renewables', 'Biofuels', 'Solar',
       'Wind', 'Hydropower', 'Nuclear', 'Gas', 'Coal', 'Oil'],
      dtype='str')

,Entity,Code,Year,Other renewables,Biofuels,Solar,Wind,Hydropower,Nuclear,Gas,Coal,Oil
0,Africa,NaN,1965,0.0,0.0,0.0,0.0,38.626762,0.0,9.571930,323.49615,341.07257
1,Africa,NaN,1966,0.0,0.0,0.0,0.0,43.083344,0.0,10.698092,323.12222,369.46457
2,Africa,NaN,1967,0.0,0.0,0.0,0.0,44.973988,0.0,10.573844,330.29160,368.28156
3,Africa,NaN,1968,0.0,0.0,0.0,0.0,52.606503,0.0,10.717145,343.51288,389.57162
4,Africa,NaN,1969,0.0,0.0,0.0,0.0,61.391357,0.0,12.520175,346.64288,397.37260

In [ ]:
df.isna().sum()

Entity                 0
Code                2378
Year                   0
Other renewables    1912
Biofuels             260
Solar               1912
Wind                1912
Hydropower          1912
Nuclear              458
Gas                 1912
Coal                1912
Oil                 1912
dtype: int64

In [ ]:
#cleaning column names
df.columns = df.columns.str.lower()

In [ ]:
# replacing spaces with underscores in column names
df.columns = df.columns.str.replace(" ", "_")

In [ ]:
#renaming the 'entity' column to 'country'
df = df.rename(columns={"entity": "country"})

In [ ]:
# Check NaN distribution before filling
print(df.isna().sum())
# Alternative: Fill with column means instead of 0
df.fillna(df.mean(numeric_only=True), inplace=True)

country                0
code                2378
year                   0
other_renewables    1912
biofuels             260
solar               1912
wind                1912
hydropower          1912
nuclear              458
gas                 1912
coal                1912
oil                 1912
dtype: int64

,country,code,year,other_renewables,biofuels,solar,wind,hydropower,nuclear,gas,coal,oil
0,Africa,NaN,1965,0.00000,0.0,0.000000,0.000000,38.626762,0.0,9.571930,323.496150,341.072570
1,Africa,NaN,1966,0.00000,0.0,0.000000,0.000000,43.083344,0.0,10.698092,323.122220,369.464570
2,Africa,NaN,1967,0.00000,0.0,0.000000,0.000000,44.973988,0.0,10.573844,330.291600,368.281560
3,Africa,NaN,1968,0.00000,0.0,0.000000,0.000000,52.606503,0.0,10.717145,343.512880,389.571620
4,Africa,NaN,1969,0.00000,0.0,0.000000,0.000000,61.391357,0.0,12.520175,346.642880,397.372600
...,...,...,...,...,...,...,...,...,...,...,...,...
8312,Zimbabwe,ZWE,2020,42.55275,0.0,23.625811,48.691258,379.975275,0.0,1284.206388,1682.740233,2304.061156
8313,Zimbabwe,ZWE,2021,42.55275,0.0,23.625811,48.691258,379.975275,0.0,1284.206388,1682.740233,2304.061156
8314,Zimbabwe,ZWE,2022,42.55275,0.0,23.625811,48.691258,379.975275,0.0,1284.206388,1682.740233,2304.061156
8315,Zimbabwe,ZWE,2023,42.55275,0.0,23.625811,48.691258,379.975275,0.0,1284.206388,1682.740233,2304.061156
8316,Zimbabwe,ZWE,2024,42.55275,0.0,23.625811,48.691258,379.975275,0.0,1284.206388,1682.740233,2304.061156

In [ ]:
df.head()

,country,code,year,other_renewables,biofuels,solar,wind,hydropower,nuclear,gas,coal,oil
0,Africa,NaN,1965,0.0,0.0,0.0,0.0,38.626762,0.0,9.571930,323.49615,341.07257
1,Africa,NaN,1966,0.0,0.0,0.0,0.0,43.083344,0.0,10.698092,323.12222,369.46457
2,Africa,NaN,1967,0.0,0.0,0.0,0.0,44.973988,0.0,10.573844,330.29160,368.28156
3,Africa,NaN,1968,0.0,0.0,0.0,0.0,52.606503,0.0,10.717145,343.51288,389.57162
4,Africa,NaN,1969,0.0,0.0,0.0,0.0,61.391357,0.0,12.520175,346.64288,397.37260

## Comparison of Fossil Fuel Consumption

**Analytical Question**  
Which fossil fuel dominates global energy consumption today: oil or coal?

**Analytical Task**  
Comparison across categories.

**Visual Idiom**  
Bar chart

**Why this idiom fits**  
Bar charts allow clear comparison of magnitudes across discrete categories. Since we are comparing total consumption of oil and coal, the bar chart allows viewers to easily see which energy source has the larger value.

**Alternative idiom**  
A stacked bar chart could also compare the total consumption of oil and coal. However, because the goal is to compare two separate category values directly, a simple bar chart is a stronger choice. A stacked bar would make the comparison less immediate because one category would not share the same baseline.

**Main Takeaway**  
Oil contributes significantly more to global energy consumption than coal in 2024.

In [ ]:
latest_year = df["year"].max()

latest_df = df[df["year"] == latest_year]

global_energy = latest_df[["oil","coal"]].sum().reset_index()

global_energy.columns = ["energy_source","consumption"]

global_energy

  energy_source    consumption
0           oil  424575.247729
1          coal  341333.611355

In [ ]:
# Sort so smaller value appears first (for horizontal bars)
global_energy_sorted = global_energy.sort_values("consumption", ascending=True)

fig1 = px.bar(
    global_energy_sorted,
    x="consumption",
    y="energy_source",
    orientation="h",
    text="consumption",
    title=f"Total Global Energy Consumption from Oil vs Coal ({latest_year})",
    labels={
        "consumption": "Total Energy Consumption (TWh)",
        "energy_source": ""
    }
)

fig1.update_traces(
    texttemplate='%{text:,.0f}',
    textposition="outside",
    marker_color=['#1f77b4', '#ff7f0e']
)

fig1.update_layout(
    showlegend=False,
    plot_bgcolor='white',
    title_x=0.5,
    height=400,
    margin=dict(l=100, r=80, t=60, b=40),
    xaxis=dict(
        gridcolor='lightgray',
        range=[0, global_energy_sorted["consumption"].max() * 1.15]  # start at 0 and add space
    )
)

fig1.show()

## Composition (Energy Mix by Country)

**Analytical Question**  
How does the energy mix differ between major economies?

**Analytical Task**  
Composition (how a whole is divided into parts).

**Visual Idiom**  
Stacked bar chart.

**Why this idiom fits**  
Stacked bar charts allow viewers to compare both total energy consumption and the relative contribution of each energy source within each country using a shared baseline.

**Alternative idiom**  
A grouped bar chart could also display the energy sources across countries. However, grouped bars make it harder to understand the overall composition of each country’s energy consumption, while stacked bars clearly show how the sources combine to form the total.

**Main Takeaway**  
Countries show distinct energy profiles: China relies heavily on coal, the United States has a more balanced mix of oil and gas, while countries like Brazil show a higher share of renewable energy sources.

In [ ]:
# Convert wide data to long format
energy_data = df.melt(
    id_vars=["country", "year"],
    value_vars=[
        "oil", "coal", "gas", "nuclear",
        "hydropower", "solar", "wind",
        "biofuels", "other_renewables"
    ],
    var_name="energy_source",
    value_name="consumption"
)

In [ ]:
latest_data = energy_data[energy_data["year"] == latest_year]

In [ ]:
# Choose major countries for the visualization
selected_countries = [
    "China",
    "United States",
    "India",
    "Russia",
    "Japan",
    "Germany",
    "Brazil",
    "Canada"
]

top_data = latest_data[latest_data["country"].isin(selected_countries)]

In [ ]:
fig = px.bar(
    top_data,
    x="country",
    y="consumption",
    color="energy_source",
    title=f"Energy Mix by Country ({latest_year})",
    labels={
        "consumption": "Energy Consumption (TWh)",
        "country": "",
        "energy_source": "Energy Source"
    },
    category_orders={
        "country": selected_countries,
        "energy_source": [
            "oil", "coal", "gas", "nuclear",
            "hydropower", "solar", "wind",
            "biofuels", "other_renewables"
        ]
    }
)

fig.update_layout(
    barmode="stack",
    plot_bgcolor="white",
    title_x=0.5,
    height=500,
    xaxis=dict(tickangle=45),
    yaxis=dict(gridcolor="lightgray"),
    legend_title_text="Energy Source"
)

fig.show()

In [ ]:
plot = fig.to_html(full_html=False, include_plotlyjs= False)

html = f'''
{plot}
<footer style="margin-top:20px; font-size:14px; color:#555;">
<p>
The stacked chart shows that fossil fuels dominate energy use across major economies, 
but the composition varies significantly by country. 
China relies heavily on coal, while the United States depends more on oil and gas, 
and renewables contribute a smaller but growing share.
</p>

</footer> 
'''

with open("./1.html", "w") as f:
    f.write(html)

## Misleading Visualization – Distorted Energy Mix by Country

**Analytical Question**  
How does the energy mix differ between major economies?

**Analytical Task**  
Composition comparison across countries.

**Visual Idiom**  
Stacked bar chart.

**Type of Misleading Technique**  
Distortion (truncated y-axis) and non-logical ordering of categories.

**Description of the Issue**  
This visualization truncates the y-axis so it does not start at zero, and the countries are intentionally not ordered by total energy consumption. Since stacked bar height represents total magnitude, altering the baseline and ordering distorts how differences are perceived.

**Why This Is Misleading**  
The truncated axis visually compresses differences, making countries with much lower energy consumption appear closer in magnitude to larger economies like China and the United States. In addition, the non-sequential ordering of countries prevents viewers from easily recognizing the true ranking of total consumption. Together, these design choices create a discrepancy between the visual impression and the actual data.

**Main Takeaway (Misleading Interpretation)**  
The chart suggests that major economies have comparable levels of total energy consumption and similar energy profiles.

**Reality**  
In reality, countries such as China and the United States consume significantly more energy than others. The apparent similarity is a result of the truncated axis and reordered categories, not the underlying data.

In [ ]:
#  misleading visualization, which exaggerates the differences between countries. 

fig3 = px.bar(
    top_data,
    x="country",
    y="consumption",
    color="energy_source",
    title=f"Energy Mix by Country ({latest_year})",
    labels={
        "consumption": "Energy Consumption (TWh)",
        "country": "",
        "energy_source": "Energy Source"
    },
    category_orders={
        "country": ["Germany", "Japan", "Brazil", "Canada", "Russia", "India", "United States", "China"]
    }
)

fig3.update_layout(
    barmode="stack",
    plot_bgcolor="white",
    title_x=0.5,
    height=500,
    xaxis=dict(tickangle=45),
    yaxis=dict(
        gridcolor="lightgray",
        range=[3000, top_data["consumption"].max()]  # misleading cropped axis
    ),
    legend_title_text="Energy Source"
)

fig3.show()